
#
# travis-ci configuration
# - reference: https://github.com/boostorg/hana/blob/master/.travis.yml
#

language: c++
sudo: false

env:
  matrix: # Workaround for https://github.com/travis-ci/travis-ci/issues/4681
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

addons:
  apt:
    packages:
      - g++-6
    sources: &sources
      - ubuntu-toolchain-r-test

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true

  include:
    - os: linux
      env: GCC_VERSION=6
      compiler: gcc

before_install:
  - export CHECKOUT_PATH=${PWD};

  - cmake --version
  - mkdir -p cmake && cd cmake
  - curl -sSL https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz | tar -xzC .
  - export PATH=${PWD}/cmake-3.5.2-Linux-x86_64/bin:${PATH}
  - cmake --version

  - export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"
  - $CXX --version

install:
  - cd $CHECKOUT_PATH

  - mkdir -p build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

script:
  - make verify

notifications:
  email: false
