
#
# travis-ci configuration
# - reference: https://github.com/boostorg/hana/blob/master/.travis.yml
#

language: cpp
matrix:
  include:
    - os: linux
      env: LLVM_VERSION=3.8.0 BUILD_TYPE=Release
      compiler: clang

# Install dependencies
before_install:
  # Install CMake
  - |
    curl -sSL https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz | sudo tar -xzC /opt
    export PATH=/opt/cmake-3.5.2-Linux-x86_64/bin:${PATH}

  - export CHECKOUT_PATH=`pwd`;

  - which $CC
  - which $CXX
  - $CXX --version

install:
  - cd $CHECKOUT_PATH

  - mkdir -p build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

script:
  - make verify

notifications:
  email: false
